### ISSUE TITLE
Need output from helm chart deployment on EKS

### ISSUE THREAD

**Issue by pkurra2020** [terraform-module/terraform-helm-release#2]
### Description of Problem:
Need to output the external ip / elb dns name of the helm chart (like apache) deployed on AWS EKS.

When deploying helm chart I want to output the information related to the deployment  so I can use the outputs later in my terraform.

### Potential Solutions:
Output the resulting json for all the resources created by helm chart in a way that is usable by terraform.

**Comment by ivankatliarchuk** [comment]
Hi. Do you have any example of it? I can add no problem.
