### ISSUE TITLE
Unable to set timeout on chart

### ISSUE THREAD

**Issue by damonconway** [terraform-module/terraform-helm-release#48]
* [x] I've searched for similar [issues](../issues) and didn't find any solution

### 💻 Environment

- Module version: 2.8.0

### 💯 Expected behavior
I expect to be able to set app.timeout, and have that reflected in helm_release.this.

### 🐞 Actual behavior
The timeout is always the default of 300.

### Bug description
**Full code that generated the error**

```js
locals {
  app_defaults = {
    deploy                = 1
    name                  = "identity-platform"
    chart                 = "identity-platform"
    version               = null
    create_namespace      = true
    reuse_values          = false
    reset_values          = true
    force_update          = true
    max_history           = 12
    render_subchart_notes = false
    timeout               = 600
  }

  values_defaults = {
    timestamp     = timestamp()
    ldif_importer = false
    storage = {
      storage_class = {
        name = "fast"
        create = {
          provisioner = "pd.csi.storage.gke.io"
          parameters = {
            type = "pd-ssd"
          }
        }
      }
      volume_snapshot_class = {
        name = "ds-snapshot-class"
        create = {
          driver = "pd.csi.storage.gke.io"
        }
      }
    }
  }
}

module "identity_platform" {
  source  = "terraform-module/release/helm"
  version = "2.8.0"

  namespace     = var.namespace
  repository    = var.repository
  app           = merge(local.app_defaults, var.app)
  set           = var.set
  set_sensitive = var.set_sensitive
  values        = flatten([yamlencode(local.values_defaults), var.values])
}
```

## 💁 Possible Solution

Add `timeout = try(var.app.timeout, 300)` to helm_release.this.

### Are you willing to resolve this issue by submitting a Pull Request❓

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ivankatliarchuk** [comment]
Hi @damonconway . Thank you for you contribution. Added to latest chart release
